# Generated by Django 2.1.7 on 2019-05-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar_do_carro_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FipeFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo_code', models.CharField(max_length=200)),
                ('modelo_nome', models.CharField(max_length=200)),
                ('ano', models.CharField(max_length=200)),
                ('potencia', models.CharField(max_length=200)),
                ('transm', models.CharField(max_length=200)),
                ('preco', models.CharField(max_length=200)),
                ('data_processamento', models.CharField(max_length=200)),
            ],
        ),
    ]
